### ISSUE TITLE
Что-то не могу получить информацию из директории

### ISSUE THREAD

**Issue by ikulichkov** [Kolyaj/yandex-disk#10]
```
import { YA_TOKEN } from './constants'

import { YandexDisk } from 'yandex-disk'

const disk = new YandexDisk(YA_TOKEN);
disk.readdir('/', function(err, data) {
  if (err) {
    console.error(err);
    return;
  }
  console.log('data: ', data);
});
```

Здравствуйте, что я делаю не так? 
Диск возвращает  "disk:  { _auth: 'OAuth e929592casdgzxdf342f98d1b2ea', _workDir: '/' }"

А дальше "Error: Auth error"

**Comment by Kolyaj** [comment]
Добрый день! 

Если после OAuth ваш токен, то он какой-то неправильный. У Яндексе токены другого вида. Вот здесь есть, как можно получить отладочный токен: https://yandex.ru/dev/id/doc/dg/oauth/tasks/get-oauth-token.html

**Comment by ikulichkov** [comment]
Я руками протыкал по клавишам середину токена.

Сб, 18 февр. 2023 г. в 20:07, Kolyaj ***@***.***>:

**Comment by Kolyaj** [comment]
Чтобы убедиться, что дело не в токене: у вас что-то похожее на это? 

PAt-_hyMQkdANA0B7M6aDK5cgAy-4VksCmTAoAtSVhRuF_bTAAQAAJAAAG

**Comment by ikulichkov** [comment]
Я теперь понял, что токен я не получил. 
Инструкция вроде очень простая, но после перехода: по ссылке 
```
https://oauth.yandex.ru/authorize?
   response_type=code&client_id=32a777801c0d4f08a96ae763a6786044
```
я получаю `http://localhost:12345/?code=1774194.`
Токен не приходит.
Глянул видос в ютуб, у человека нормального, после такого же запроса, сразу выдает токен

**Comment by Kolyaj** [comment]
Если вам токен только для себя, то есть можно отладочный, то в Callback URI у приложения должно быть https://oauth.yandex.ru/verification_code?dev=true, эта страница покажет вам токен.

Если вам нужно реализовать получение токена для пользователя, то по коду, который в вашем комментарии, нужно получить токен https://yandex.ru/dev/id/doc/dg/oauth/reference/auto-code-client.html

**Comment by ikulichkov** [comment]
Получил отладочный токен, вставил в код, все равно `Error: Auth error`

**Comment by Kolyaj** [comment]
Возможно у токена нет прав на доступ к диску.

**Comment by ikulichkov** [comment]
```

const client_id = CLIENT_ID;
const client_secret = CLIENT_SECRET;
const baseurl = 'https://oauth.yandex.ru/';

const app = express();

app.use(bodyParser.urlencoded({ extended: false }));

app.get('/', function (req, res) {
  if (req.query.code) {
    const data = {
      grant_type: 'authorization_code',
      code: req.query.code,
      client_id: client_id,
      client_secret: client_secret,
    };
    request.post({
      url: baseurl + 'token',
      form: data,
    }, function (err, response, body) {
      if (err) {
        console.error(err);
        res.status(500).send('Ошибка получения токена');
      } else {
        res.send(JSON.parse(body));
      }
    });
  } else {
    const params = querystring.stringify({
      response_type: 'code',
      client_id: client_id,
    });
    res.redirect(baseurl + 'authorize?' + params);
  }
});

app.listen(8000, function () {
  console.log('Сервер запущен на порту 8000');
});
```
Возвращает код, токена нет, это какая-то жесть)
