### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by TheGP** [Kolyaj/yandex-disk#9]
хз как делать листинг директорий

**Comment by Kolyaj** [comment]
disk.readdir(path, callback) - читает содержимое директории. Результатом является массив объектов с полями

    href - путь к файлу на Я.Диске
    displayName - отображаемое имя
    creationDate - дата создания (строка)
    isDir - если это директория, то true
    size - если это файл, то размер файла, иначе 0
    lastModified - дата последней модификации (строка)

**Comment by TheGP** [comment]
не читает :app/

**Comment by Kolyaj** [comment]
Опишите проблему нормально, что вы по два слова пишете? Какой :app/? Какая ошибка возникает? Покажите код, в конце концов.

**Comment by Kolyaj** [comment]
В проекте есть тесты, запустите node tests login password, где login/password – логин пароль от Яндекса. Тест на чтение директории срабатывает нормально. Можно там код посмотреть.
